### ISSUE TITLE
Move ML Blocks to single git repo

### ISSUE THREAD

**Issue by rad-rad** [ascentcore/ml-blocks#69]
Bring all the following repos together into - ac-ml-blocks(private repo)

ml-blocks-generic - base building block that contains common functionalities
ml-blocks-infer - inference block built on top of generic
ml-blocks-train - training block build on top of generic
ml-blocks-supervisor - orchestrator block that manages infers and train
ml-blocks-playground - POCs and use cases - all above repos are referenced here
ml-blocks-data-storage - TBD
ml-blocks-auth - TBD

remove redundant naming of folders and update docker files and imports
refactor any irelevant code after move to single repo (git submodules folders and mentions)
any other improvements to the setup are very welcomed

**Comment by ac-otto-tamas** [comment]
To avoid doing unnecessary work for replacing the submodule refs with some os primitives, for this ticket we will try to introduce poetry for python package management. Scope is to make it work with minimal changes to the structure of the repositories, further enhancements will be discussed and treated with dedicated issues.

https://python-poetry.org/

**Comment by ac-otto-tamas** [comment]
Monorepo is created and poetry is used only for generic. As a second step we'll bring the structure closer to standardized python package and will use poetry for all blocks. This is going to be a bit more exhaustive task (it is what it is :) ).

**Comment by ac-otto-tamas** [comment]
Current state presented and we decided to move forward.

Prioritized TODO:

- chatbot application refactoring. Rename examples to app
- merge to main
- refactor auth and supervisor
- move to an `old` directory plugins and ui

**Comment by ac-otto-tamas** [comment]
Refactored chatbot application and created a PR to main with current changes: https://github.com/ascentcore/ac-ml-blocks/pull/78

TODO:

- refactor auth and supervisor
- move to an old directory plugins and ui
- refactor other apps
- check if .env file can be reused in docker compose with an override.env for variables that are not common.

**Comment by ac-otto-tamas** [comment]
Refactored auth block, added poetry pre-commit hooks and added docker testing utility for standalone blocks: https://github.com/ascentcore/ac-ml-blocks/pull/82. 

Also .env file is reworked to not contain duplicates, only overrides for docker environment in a previous PR.

TODO: 
 - refactor supervisor
 - deprecate other blocks.

**Comment by ac-otto-tamas** [comment]
Actually in today's daily we decided to archive the supervisor block for now. With that being said, this issue is considered done.
